name:                lake-parser-combinators
version:             0.1.0.0
github:              "githubuser/lake-parser-combinators"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lake-parser-combinators#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- containers

library:
  source-dirs: src

executables:
  lake-parser-combinators-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lake-parser-combinators

tests:
  lake-parser-combinators-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lake-parser-combinators
    - hspec
    - hspec-contrib
    - QuickCheck
    - HUnit
